Add options for cardinal/ordinal plural types
projectfluent/fluent-rs pull request #259
Opened 2022-06-25 21:25 UTC by oliver-ni

Adds functionality for switching between plural types (cardinal and ordinal).

Fluent docs include this option in the `NUMBER` built-in function. Since `fluent-rs` doesn't have that yet, I included it in the place where all the other number options were. Please let me know if this isn't the appropriate place / way to include this functionality.

Also, I called it `kind` instead of `type` since the latter is a Rust keyword... a little weird but not sure if there's a better way to deal with that.

2022-07-26 19:45 UTC, juliancoffee commented
@oliver-ni to answer on using "type" in Rust, you can use raw identifiers.
https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html

2022-10-27 15:38 UTC, gregtatum requested changes
The changes look reasonable, but I have a few requested changes.

> @oliver-ni to answer on using "type" in Rust, you can use raw identifiers.

Thought: I think I prefer `kind` here, it's used other places in the codebase.

Suggestion: This code is missing tests. It would probably be good to add some unit tests to the file, and see if there are relevant areas that an integration test could be added.

2022-10-27 15:38 UTC, gregtatum commented on fluent-bundle/src/types/number.rs
> +pub enum FluentNumberKind {
Suggestion: Please add docs here, with a link to the relevant Fluent documentation, and an example of what the `.ftl` syntax looks like.

2023-09-08 15:56 UTC, gregtatum commented
Closing as stale.

2023-09-08 15:56 UTC, closed without merging